#!/bin/bash
export JDTLS_ROOT=${HOME}/data/jdtls
export WORKSPACE=${HOME}/data/workspace
export GRADLE_HOME=${HOME}/data/gradle

java \
     -Declipse.application=org.eclipse.jdt.ls.core.id1 \
     -Dosgi.bundles.defaultStartLevel=4 \
     -Declipse.product=org.eclipse.jdt.ls.core.product \
     -Dlog.protocol=true \
     -Dlog.level=ALL \
     -Xms1G \
     -Xmx2G \
     -jar ${JDTLS_ROOT}/plugins/org.eclipse.equinox.launcher_1.6.100.v20201223-0822.jar \
     -configuration ${JDTLS_ROOT}/config_linux \
     -data ${1:-WORKSPACE} \
     --add-modules=ALL-SYSTEM \
     --add-opens java.base/java.util=ALL-UNNAMED \
     --add-opens java.base/java.lang=ALL-UNNAMED
